### ISSUE TITLE
Get to know rails Rails ?

### ISSUE THREAD

**Issue by dixpac** [maclover7/ama#11]
Hi,
Do you have some advices how to understand Rails behind scenes, to get great understanding how everything works? There are a lot of things happening in code and I feel every time I try to understand one part of the framework I always drift in land of unknown :)

**Comment by maclover7** [comment]
I haven't read it, but I have heard _really_ good things about José Valim's "Crafting Rails 4 Applications". Also, when trying to learn Rails behind-the-scenes stuff, know that everything is still in Ruby, and it's a Ruby application (albeit a very large one with tons of components) just like any other project you've worked on. I'd say to try and read through how cool things like the routing system works, associations in `ActiveRecord` work, etc. If you really want to get deep into Rails, you follow [this book](https://rebuilding-rails.com/) and build a simple replacement, while learning how Rails internals work.

Thanks for the question!
