### ISSUE TITLE
Did you enjoy your experience at your summer job?

### ISSUE THREAD

**Issue by Nikolay-Pomytkin** [maclover7/ama#5]
This is a re-ask of: https://github.com/maclover7/ama/issues/4

Could you describe some info about your experience?

**Comment by maclover7** [comment]
I definitely enjoyed the experience of my summer job. Was a lot of fun to take the train into Manhattan and ride the subway everyday. Everyone at my workplace was very nice. Also enjoyed MC'ing a 50 person Rails meetup while I was working over the summer.
