### ISSUE TITLE
How did you get started contributing to rails?

### ISSUE THREAD

**Issue by treble37** [maclover7/ama#9]
Hi maclover7, saw your contribution in the rails weekly newsletter...just wondering - how did you get started contributing to rails?  Just built a lot of apps and ran into thorny problems?  Interested in your telling of the story as it were...

**Comment by maclover7** [comment]
Interesting question! I think I first started by opening up tickets for issues I began seeing in my applications. Over time, I have tried to go through and triage issues over many weaves. Most recently, I've joined the Rails Issues Team, and have been landing some pretty neat PRs into Rails. The best way to get started with contributing is to either report a bunch of bugs, try and fix existing bugs, or go through old issues and PRs.
